// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemaVeterinario.Models;

#nullable disable

namespace sistemaVeterinario.Migrations
{
    [DbContext(typeof(SistemaVeterinarioContext))]
    [Migration("20251019193237_MakeDiagnosticoNullable")]
    partial class MakeDiagnosticoNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sistemaVeterinario.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Run")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("run");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente")
                        .HasName("PK__clientes__677F38F5448FD6C5");

                    b.HasIndex(new[] { "Email" }, "UQ__clientes__AB6E6164286AA167")
                        .IsUnique();

                    b.HasIndex(new[] { "Run" }, "UQ__clientes__C2B74E6CB8485CC1")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Consulta", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_consulta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsulta"));

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text")
                        .HasColumnName("diagnostico");

                    b.Property<DateOnly>("FechaConsulta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_consulta");

                    b.Property<int>("IdEstadoConsulta")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_consulta");

                    b.Property<int>("IdMascota")
                        .HasColumnType("int")
                        .HasColumnName("id_mascota");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.HasKey("IdConsulta")
                        .HasName("PK__consulta__6F53588BC63A384F");

                    b.HasIndex("IdEstadoConsulta");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdUsuario");

                    b.ToTable("consultas", (string)null);
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Especy", b =>
                {
                    b.Property<int>("IdEspecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_especie");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecie"));

                    b.Property<string>("NombreEspecie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre_especie");

                    b.HasKey("IdEspecie")
                        .HasName("PK__especies__96DDB0B982955345");

                    b.ToTable("especies", (string)null);

                    b.HasData(
                        new
                        {
                            IdEspecie = 1,
                            NombreEspecie = "Perro"
                        },
                        new
                        {
                            IdEspecie = 2,
                            NombreEspecie = "Gato"
                        },
                        new
                        {
                            IdEspecie = 3,
                            NombreEspecie = "Hámster"
                        },
                        new
                        {
                            IdEspecie = 4,
                            NombreEspecie = "Conejo"
                        },
                        new
                        {
                            IdEspecie = 5,
                            NombreEspecie = "Ave"
                        });
                });

            modelBuilder.Entity("sistemaVeterinario.Models.EstadoConsulta", b =>
                {
                    b.Property<int>("IdEstadoConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado_consulta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoConsulta"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("nombre_estado");

                    b.HasKey("IdEstadoConsulta")
                        .HasName("PK__estado_c__19A53235F51D74B3");

                    b.ToTable("estado_consultas", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoConsulta = 1,
                            NombreEstado = "Pendiente"
                        },
                        new
                        {
                            IdEstadoConsulta = 2,
                            NombreEstado = "En Progreso"
                        },
                        new
                        {
                            IdEstadoConsulta = 3,
                            NombreEstado = "Finalizada"
                        });
                });

            modelBuilder.Entity("sistemaVeterinario.Models.EstadoUsuario", b =>
                {
                    b.Property<int>("IdEstadoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoUsuario"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("nombre_estado");

                    b.HasKey("IdEstadoUsuario")
                        .HasName("PK__estado_u__CEFB9B89DD0EA143");

                    b.ToTable("estado_usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoUsuario = 1,
                            NombreEstado = "Activo"
                        },
                        new
                        {
                            IdEstadoUsuario = 2,
                            NombreEstado = "Inactivo"
                        });
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mascota");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMascota"));

                    b.Property<int?>("Edad")
                        .HasColumnType("int")
                        .HasColumnName("edad");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEspecie")
                        .HasColumnType("int")
                        .HasColumnName("id_especie");

                    b.Property<int>("IdRaza")
                        .HasColumnType("int")
                        .HasColumnName("id_raza");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Sexo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("sexo")
                        .IsFixedLength();

                    b.HasKey("IdMascota")
                        .HasName("PK__mascotas__6F0373524828A893");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEspecie");

                    b.HasIndex("IdRaza");

                    b.ToTable("mascotas", (string)null);
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Raza", b =>
                {
                    b.Property<int>("IdRaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_raza");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRaza"));

                    b.Property<string>("NombreRaza")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre_raza");

                    b.HasKey("IdRaza")
                        .HasName("PK__razas__084F250A6A7054C8");

                    b.ToTable("razas", (string)null);

                    b.HasData(
                        new
                        {
                            IdRaza = 1,
                            NombreRaza = "Labrador"
                        },
                        new
                        {
                            IdRaza = 2,
                            NombreRaza = "Poodle"
                        },
                        new
                        {
                            IdRaza = 3,
                            NombreRaza = "Siamés"
                        },
                        new
                        {
                            IdRaza = 4,
                            NombreRaza = "Persa"
                        },
                        new
                        {
                            IdRaza = 5,
                            NombreRaza = "Dorado"
                        },
                        new
                        {
                            IdRaza = 6,
                            NombreRaza = "Cabeza de León"
                        },
                        new
                        {
                            IdRaza = 7,
                            NombreRaza = "Canario"
                        });
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol")
                        .HasName("PK__roles__6ABCB5E0E52DCD0F");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tratamiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTratamiento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdConsulta")
                        .HasColumnType("int")
                        .HasColumnName("id_consulta");

                    b.Property<string>("Medicamento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("medicamento");

                    b.HasKey("IdTratamiento")
                        .HasName("PK__tratamie__C8825F4CB6B1F22C");

                    b.HasIndex("IdConsulta");

                    b.ToTable("tratamientos", (string)null);
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("IdEstadoUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_usuario");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("password");

                    b.HasKey("IdUsuario")
                        .HasName("PK__usuarios__4E3E04AD4CB7E388");

                    b.HasIndex("IdEstadoUsuario");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Email" }, "UQ__usuarios__AB6E616446B1A300")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Consulta", b =>
                {
                    b.HasOne("sistemaVeterinario.Models.EstadoConsulta", "IdEstadoConsultaNavigation")
                        .WithMany("Consulta")
                        .HasForeignKey("IdEstadoConsulta")
                        .IsRequired()
                        .HasConstraintName("FK__consultas__id_es__534D60F1");

                    b.HasOne("sistemaVeterinario.Models.Mascota", "IdMascotaNavigation")
                        .WithMany("Consulta")
                        .HasForeignKey("IdMascota")
                        .IsRequired()
                        .HasConstraintName("FK__consultas__id_ma__5165187F");

                    b.HasOne("sistemaVeterinario.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Consulta")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__consultas__id_us__52593CB8");

                    b.Navigation("IdEstadoConsultaNavigation");

                    b.Navigation("IdMascotaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Mascota", b =>
                {
                    b.HasOne("sistemaVeterinario.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Mascota")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK__mascotas__id_cli__4CA06362");

                    b.HasOne("sistemaVeterinario.Models.Especy", "IdEspecieNavigation")
                        .WithMany("Mascota")
                        .HasForeignKey("IdEspecie")
                        .IsRequired()
                        .HasConstraintName("FK__mascotas__id_esp__4D94879B");

                    b.HasOne("sistemaVeterinario.Models.Raza", "IdRazaNavigation")
                        .WithMany("Mascota")
                        .HasForeignKey("IdRaza")
                        .IsRequired()
                        .HasConstraintName("FK__mascotas__id_raz__4E88ABD4");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEspecieNavigation");

                    b.Navigation("IdRazaNavigation");
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Tratamiento", b =>
                {
                    b.HasOne("sistemaVeterinario.Models.Consulta", "IdConsultaNavigation")
                        .WithMany("Tratamientos")
                        .HasForeignKey("IdConsulta")
                        .IsRequired()
                        .HasConstraintName("FK__tratamien__id_co__5629CD9C");

                    b.Navigation("IdConsultaNavigation");
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Usuario", b =>
                {
                    b.HasOne("sistemaVeterinario.Models.EstadoUsuario", "IdEstadoUsuarioNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEstadoUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__usuarios__id_est__47DBAE45");

                    b.HasOne("sistemaVeterinario.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__usuarios__id_rol__46E78A0C");

                    b.Navigation("IdEstadoUsuarioNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Cliente", b =>
                {
                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Consulta", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Especy", b =>
                {
                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("sistemaVeterinario.Models.EstadoConsulta", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("sistemaVeterinario.Models.EstadoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Mascota", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Raza", b =>
                {
                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("sistemaVeterinario.Models.Usuario", b =>
                {
                    b.Navigation("Consulta");
                });
#pragma warning restore 612, 618
        }
    }
}
